config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users

  post 'add_to_wishlist', to: 'users#add_to_wishlist'
  delete 'remove_from_wishlist', to: 'users#remove_from_wishlist'

  post 'add_to_ownlist', to: 'users#add_to_ownlist'
  delete 'remove_from_ownlist', to: 'users#remove_from_ownlist'

  post 'answer_proposal', to: 'users#answer_proposal'
  post 'answer_match', to: 'users#answer_match'

  get '/profile', to: 'pages#profile'
  get '/collection', to: 'pages#collection'
  get '/search', to: 'pages#search', as: :search
end

app/views/pages/collection.html.erb
<% unless !user_signed_in? %>
<% fetcher = Resource::GameFetcher.new GiantBomb::Game.method(:detail) %>

  <div class="container">
    <div class="row games-row">
      <div class="col-md-6">
        <nav class="navbar navbar-dark bg-primary">
          <h2><a class="navbar-brand">Desejados</a></h2>
        </nav>
        <div class="row">
          <% if @wishes.empty? %>
            <div class="col-md-12">
              <h6 class="mt-3 text-secondary">Você ainda não adicionou nenhum jogo à lista de desejados.</h6>
            </div>
          <% else %>
            <% @wishes.each do |wish| %>
              <div class="col-md-4 col-6 card-col">
                <div class="card mb-0 bg-dark text-white">
                  <%= image_tag find_game(fetcher, wish.game_id, 'image'), class: "card-img game-pic" %> 
                  
                  <div class="card-img-overlay flex-column d-flex justify-content-center text-center">
                    <p class="font-weight-bold"><%= find_game(fetcher, wish.game_id, 'name') %></p>
                    <%= link_to 'Remover', remove_from_wishlist_path(id: wish.game_id), method: :delete,
                    remote: true, class: "btn btn-danger delete " %>
                  </div>
                </div> 
              </div> <!-- Col-md-4 -->
            <% end %>
          <% end %>
        </div>
      </div> <!-- Col-md-6 -->

      <div class="col-md-6">
        <nav class="navbar navbar-dark bg-warning">
          <h2><a class="navbar-brand text-dark">Para trocar</a></h2>
        </nav>
        <div class="row">
          <% if @owns.empty? %>
            <div class="col-md-12">
              <h6 class="mt-3 text-secondary">Você ainda não adicionou nenhum jogo para realizar trocas.</h6>
            </div>
          <% else %>
            <% @owns.each do |own| %>
            <div class="col-md-4 col-6 card-col">
              <div class="card mb-0 bg-dark text-white">
                <%= image_tag find_game(fetcher, own.game_id, 'image'), class: "card-img game-pic" %>
                <div class="card-img-overlay flex-column d-flex justify-content-center text-center">
                  <p class="font-weight-bold"><%= find_game(fetcher, own.game_id, 'name') %></p>
                  <%= link_to 'Remover', remove_from_ownlist_path(id: own.game_id), method: :delete,
                  remote: true, class: "btn btn-danger delete " %>
                </div>
              </div> 
            </div> <!-- Col-md-4 -->
            <% end %>
          <% end %>
        </div> 
      </div> <!-- Col-md-6-->
    </div>
  </div>
<% end %>

app/views/pages/index.html.erb
<!--Carrosel-->

  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" >
    <!--Imagens - Carrosel-->
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag 'https://wallpaperplay.com/walls/full/c/1/4/101203.jpg', class: 'd-block w-100 hero-img',
        style: "height: 100vh; object-fit: cover;"%>
        <div class="black-overlay">
        
        </div>
      </div>
      <div class="hero">
        <h5 class="my-3 text-primary">Bem-vindo(a) ao Escambee</h5>
        <h1 class="my-3">Troque seus jogos de maneira fácil!</h1>
        <p class="my-4">Com o Escambee, é possível fazer uma lista com os jogos que você deseja receber e selecionar
        os que você tem e quer dar e troca. Você pode ver se seus jogos desejados estão disponíveis, 
        e, então, realizar uma troca.</p>

        <%= link_to 'Criar conta', new_user_registration_path, class: "btn btn-primary p-3" %>     
      </div>  
    </div>  
  </div>


<div class="container how-it-works">
  <div class="row align-items-center">
    <div class="col-md-3">
      <h2>Como <br>funciona?</h2>
    </div>
    <div class="col-md-9">
      <div class="row steps">
        <div class="col-md-4">
          <span><i class="far fa-hand-pointer fa-3x"></i></span>
          <p>Escolha os jogos que você gostaria de <b>receber</b> e <b>dar em troca</b></p>
        </div>
        
        <div class="col-md-4">
          <span> <i class="fas fa-exchange-alt fa-3x"></i></span>
          <p>Realize uma troca e espere que outro usuário a aceite</p>
        </div>
        <div class="col-md-4">
          <span><i class="far fa-handshake fa-3x"></i></span>   
          <p class="mb-1 font-weight-bold">Troca concluída!</p> 
          <small class="text-muted">A partir do término da mesma, os usuários podem conversar sobre 
          os detalhes.</small>
        </div>
      </div>
    
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>Jogos disponíveis</h2>
      <hr>
    </div>

    <% @results.each do |game| %>
      <div class="col-md-3 col-6">
        <div class="card">
          <%= image_tag "#{game.image['original_url']}", class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= game.name%></h5>
            <% if user_signed_in? %>
              <% if current_user.can_add_in_list?(Game.new(game.id.to_s)) %> 
                <div class="btns">
                  <%= link_to 'Quero', add_to_wishlist_path(id: game.id), 
                  class: 'btn btn-primary add', method: :post, remote: true %>
                  <%= link_to 'Tenho', add_to_ownlist_url(id: game.id), 
                  class: 'btn btn-warning add', method: :post, remote: true %> 
                </div>     
              
              <% else %>
                <p class="mb-0">Jogo já adicionado na sua <%= link_to 'coleção', collection_path %>.</p>
              <% end %>
            <% else %>
              <p class="text-muted">
                <%= link_to 'Entre', new_user_session_path%> ou 
                <%= link_to 'registre-se', new_user_registration_path %> para trocar/receber este jogo!
              </p>   
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="col-md-12 d-flex text-center justify-content-center">
      <%= paginate @results, theme: 'twitter-bootstrap-4' %>
    </div>
  </div>
</div>


  
        <%#= image_tag 'https://via.placeholder.com/500x500', class: 'card-img-top' %>
        

app/views/pages/profile.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-12">
          <nav class="navbar navbar-dark bg-primary">
            <h2><a class="navbar-brand">Proposta de trocas</a></h2>
          </nav>
        </div>
        <% fetcher = Resource::GameFetcher.new GiantBomb::Game.method(:detail) %>
        <% if @proposals.empty? %>
          <div class="col-md-12 text-center mt-3">
            <h4>Nenhuma proposta disponível.</h4>
          </div>  
        <% else %>
        <% @proposals.each do |proposal| %>
          <div class="col-md-12 mt-3">
            <div class="card">
              <div class="card-body d-flex">
                <div class="proposal-div">
                  <%= image_tag find_game(fetcher, proposal.given_game(current_user).id, 'image'), class: "proposal-img"
                  %>
                  <h6 class="mt-3 mb-0 text-center"><%= find_game(fetcher, proposal.given_game(current_user).id, 'name') %></h6>
                </div>
                <div class="arrow-div px-3 text-center align-self-center"><i class="fas fa-arrow-right fa-2x text-secondary"></i></div>
                <div class="proposal-div">
                  <%= image_tag find_game(fetcher, proposal.received_game(current_user).id, 'image'), class: " proposal-img" %>
                  <h6 class="mt-3 mb-0 text-center"><%= find_game(fetcher, proposal.received_game(current_user).id, 'name')%></h6>
                </div>
              </div>
              <div class="card-footer text-center">
                <div class="btns">
                  <%= link_to 'Trocar', answer_proposal_path(answer: true, proposal_id: proposal.id), method: 'post', remote: 'true', class: "btn btn-success accept"%>
                  <%= link_to 'Não trocar', answer_proposal_path(answer: false, proposal_id: proposal.id), method: 'post', remote: 'true', class: "btn btn-danger reject"%>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>  
      </div>
    </div> <!-- Col-md-9 (Trocas) -->  

    <div class="col-md-6">
      <div class="row">
        <div class="col-md-12">
          <nav class="navbar navbar-dark bg-warning">
            <h2><a class="navbar-brand text-dark">Trocas disponíveis</a></h2>
          </nav>
        </div>
        <% if @matches.empty? %>
          <div class="col-md-12 text-center mt-3">
            <h4>Nenhuma troca disponível.</h4>
          </div>  
        <% else %>
        <% @matches.each do |match| %>
          <div class="col-md-12 mt-3">
            <div class="card">
              <div class="card-body d-flex">
                <div class="proposal-div">
                  <%= image_tag find_game(fetcher, match.proposal.given_game(current_user).id, 'image'), class: "proposal-img"
                  %>
                  <h6 class="mt-3 mb-0 text-center"><%= find_game(fetcher, match.proposal.given_game(current_user).id, 'name') %></h6>
                </div>
                <div class="arrow-div px-3 text-center align-self-center"><i class="fas fa-arrow-right fa-2x text-secondary"></i></div>
                <div class="proposal-div">
                  <%= image_tag find_game(fetcher, match.proposal.received_game(current_user).id, 'image'), class: " proposal-img" %>
                  <h6 class="mt-3 mb-0 text-center"><%= find_game(fetcher, match.proposal.received_game(current_user).id, 'name')%></h6>
                </div>
              </div>
              <p class="text-center"> Trocar com <%= match.users.find { |user| user != current_user }.name.camelize %>?</p>
              <div class="card-footer text-center">
                <div class="btns">
                  <%= link_to 'Trocar', answer_match_path(answer: true, match_id: match.id), method: :post, remote: true, class: "btn btn-success accept-exchange"%>
                <%= link_to 'Não trocar', answer_match_path(answer: false, match_id: match.id), method: :post, remote: true, class: "btn btn-danger deny-exchange"%>
                </div>          
                <div class="text-success user-info justify-content-center d-none mt-3 align-items-center">
                <h4 class="d-inline-flex mr-2 "><i class="fab fa-whatsapp"></i></h4>
                <a class="pb-2 text-success d-flex" href="https://api.whatsapp.com/send?phone=<%= match.users.find { |user| user != current_user }.phone %>">
                Conversar sobre a troca
                </a>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>  
      
      </div>
     
    </div>
  </div>
</div>

app/views/pages/search.html.erb
<div class="container">
  <div class="row">
    <% @results.each do |game| %>
      <div class="col-md-3 col-6">
        <div class="card">
          <%= image_tag "#{game['image']['original_url']}", class: 'card-img-top' %>
          <div class="card-body">
            <h5 class="card-title"><%= game['name']%></h5>
            <% if user_signed_in? %>
              <% if current_user.can_add_in_list?(Game.new(game['id'].to_s)) %> 
                <div class="btns">
                  <%= link_to 'Quero', add_to_wishlist_path(id: game['id']), 
                  class: 'btn btn-primary add', method: :post, remote: true %>
                  <%= link_to 'Tenho', add_to_ownlist_url(id: game['id']), 
                  class: 'btn btn-warning add', method: :post, remote: true %> 
                </div>     
              
              <% else %>
                <p class="mb-0">Jogo já adicionado na sua <%= link_to 'coleção', collection_path %>.</p>
              <% end %>
            <% else %>
              <p class="text-muted mb-0">
                <%= link_to 'Entre', new_user_session_path%> ou 
                <%= link_to 'registre-se', new_user_registration_path %> para trocar/receber este jogo!
              </p>
            <% end %>      
          </div>
       </div>
      </div>
    <% end %> 
    <div class="col-md-12 d-flex text-center justify-content-center">
      <%= paginate @results, theme: 'twitter-bootstrap-4' %>
    </div>
  </div>
</div>