config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users

  post 'add_to_wishlist', to: 'users#add_to_wishlist'
  delete 'remove_from_wishlist', to: 'users#remove_from_wishlist'

  post 'add_to_ownlist', to: 'users#add_to_ownlist'
  delete 'remove_from_ownlist', to: 'users#remove_from_ownlist'

  post 'answer_proposal', to: 'users#answer_proposal'
  post 'answer_match', to: 'users#answer_match'

  get '/profile', to: 'pages#profile'
  get '/collection', to: 'pages#collection'
  get '/search', to: 'pages#search', as: :search
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Escambee</title>
    <%= csrf_meta_tags %>
    <script src="https://kit.fontawesome.com/8d9d868ad3.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('bee.ico') %>
  </head>
  
  <body class="d-flex flex-column h-100">
  <div class="header">
    <% unless !user_signed_in? %>
      <nav class="navbar border-bottom navbar-expand-lg navbar-light bg-light">
        <div class="container">  
          <div class="d-inline-flex navbar-nav ml-auto" >      
            <span class="navbar-text">
              <i class="far fa-user mr-2"></i>
            </span>
            <div>
            <%= link_to "Editar informações de conta", edit_user_registration_path, class: "nav-item nav-link" %></div>
            <%= link_to "Encerrar sessão", destroy_user_session_path, method: :delete, class: "nav-item nav-link" %>   
          </div>
        </div>
      </nav>
    <% end %>  

    <div class="container main-menu">
      <div class="row align-items-center">
        
        <div class="col-lg-3 col-md-12 col-content d-flex align-items-center justify-content-md-center">
          <%= inline_svg_tag("bee.svg", class: "logo-img") %>
          <h2 class="mb-0"><%= link_to 'Escambee', root_path, class: "logotipo my-auto text-primary ml-2" %></h2>
        </div>
       
        <div class="col-lg-5 col-md-7 col-content">
          <%= form_tag search_path, method: :get do %>
          <div class="input-group">
              <%= text_field_tag :search, params[:search], placeholder: "Procurar jogo...", 
              class: "form-control", aria: { label: "Procurar jogo...", describedby: "button-addon2"} %>
              <div class="input-group-append">
                
                <%= button_tag(:submit, class: "btn btn-primary px-3", id: "button-addon2") do %>
                  <i class="fa fa-search text-light"></i>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col-lg-4 col-md-5 d-flex col-content">
          <div class="menu-container d-flex align-items-center  ">
          <% if user_signed_in? %>
          <i class="fas fa-list fa-2x"></i>
            <div class="d-flex flex-column">
              <div class="teste"><%= link_to 'Coleção', collection_path %> </div>
              <small class="text-muted">
                Deseja: <%= current_user.wishlist.count %> / Possui: <%= current_user.ownlist.count %></small>
            </div>
          
          <i class="far fa-user fa-2x ml-4"></i>
          
            <div class="d-flex flex-column">
              <div><%= link_to 'Perfil', profile_path %> </div>
              <small class="text-muted"><%= current_user.name.truncate(18) %></small>
            </div>
          </div> 
          <% else %>
            <i class="far fa-user fa-2x ml-4"></i>
         
            <div class="d-flex flex-column">
              <div><%= link_to 'Entre',  new_user_session_path %> ou 
              <%= link_to 'Registre-se', new_user_registration_path %></div>
              <div class="text-muted">para realizar trocas</div>
            </div>
          </div> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
  
  
    <% if devise_controller? %>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-7 text-center">
            <div class="card p-4">
              <%= yield %>      
            </div>     
          </div>
        </div>
      </div>
      
    <% else %>
      <%= yield %>
    <% end %>
  
  <footer class="py-4 bg-dark footer text-white-50 mt-auto">
    <div class="container text-center">
      <small>Copyright &copy; Escambee</small>
    </div>
  </footer>
  </body>
</html>